"""Fix placeholder vocabulary and grammar in German A2-C2, French A2-C2, and Portuguese A2 lessons."""
import asyncio
import os
from motor.motor_asyncio import AsyncIOMotorClient

MONGO_URL = os.environ.get("MONGO_URL")
DB_NAME = os.environ.get("DB_NAME")

GERMAN_VOCAB = {
    "A2": {
        0: {"vocab": [{"word": "Groß/Klein", "translation": "Big/Small", "example": "Das Haus ist sehr groß."}, {"word": "Hübsch", "translation": "Pretty", "example": "Die Stadt ist sehr hübsch."}, {"word": "Freundlich", "translation": "Friendly", "example": "Die Leute sind freundlich."}, {"word": "Haare", "translation": "Hair", "example": "Sie hat lange blonde Haare."}, {"word": "Augen", "translation": "Eyes", "example": "Er hat blaue Augen."}, {"word": "Ruhig", "translation": "Quiet", "example": "Das Dorf ist sehr ruhig."}], "grammar": ["Adjektivdeklination: der große Mann, ein großer Mann", "SER vs ESTAR: sein für Eigenschaften, Zustandsverben", "Komparativ und Superlativ: groß, größer, am größten"]},
        1: {"vocab": [{"word": "Wie viel kostet?", "translation": "How much?", "example": "Wie viel kostet dieses Hemd?"}, {"word": "Billig/Teuer", "translation": "Cheap/Expensive", "example": "Das Kleid ist zu teuer."}, {"word": "Größe", "translation": "Size", "example": "Haben Sie das in Größe M?"}, {"word": "Anprobieren", "translation": "To try on", "example": "Kann ich das anprobieren?"}, {"word": "Bargeld", "translation": "Cash", "example": "Kann ich bar bezahlen?"}, {"word": "Rabatt", "translation": "Discount", "example": "Gibt es einen Rabatt?"}], "grammar": ["Komparativ: billiger als, teurer als", "Demonstrativpronomen: dieser, diese, dieses", "Akkusativpronomen: mich, dich, ihn, sie, es"]},
        2: {"vocab": [{"word": "Es ist heiß", "translation": "It's hot", "example": "Im Sommer ist es sehr heiß."}, {"word": "Regen", "translation": "Rain", "example": "Es gibt viel Regen im Herbst."}, {"word": "Bewölkt", "translation": "Cloudy", "example": "Heute ist es bewölkt."}, {"word": "Frühling", "translation": "Spring", "example": "Im Frühling blühen die Blumen."}, {"word": "Regenschirm", "translation": "Umbrella", "example": "Nimm einen Regenschirm mit."}, {"word": "Grad", "translation": "Degrees", "example": "Es sind 30 Grad heute."}], "grammar": ["Unpersönliches ES: Es regnet, Es schneit, Es ist kalt", "Nebensätze mit WEIL: Es ist kalt, weil es Winter ist", "Futur mit WERDEN: Es wird morgen regnen"]},
        3: {"vocab": [{"word": "Rechts/Links", "translation": "Right/Left", "example": "Biegen Sie rechts ab."}, {"word": "Nah/Weit", "translation": "Near/Far", "example": "Das Hotel ist nah am Zentrum."}, {"word": "Ecke", "translation": "Corner", "example": "Die Apotheke ist an der Ecke."}, {"word": "Haltestelle", "translation": "Stop", "example": "Die Bushaltestelle ist hier."}, {"word": "Straße", "translation": "Street", "example": "Ich wohne in der Hauptstraße."}, {"word": "Überqueren", "translation": "To cross", "example": "Überqueren Sie die Straße."}], "grammar": ["Imperativ: Gehen Sie geradeaus, Biegen Sie ab", "Wechselpräpositionen: in, an, auf + Dativ (wo?) / Akkusativ (wohin?)", "Modalverben: können, müssen, dürfen, sollen"]},
        4: {"vocab": [{"word": "Freizeit", "translation": "Free time", "example": "In meiner Freizeit lese ich."}, {"word": "Wochenende", "translation": "Weekend", "example": "Am Wochenende gehe ich ins Kino."}, {"word": "Film", "translation": "Movie", "example": "Wollen wir einen Film sehen?"}, {"word": "Spaß", "translation": "Fun", "example": "Das hat viel Spaß gemacht."}, {"word": "Einladen", "translation": "To invite", "example": "Ich lade dich zum Essen ein."}, {"word": "Spazieren", "translation": "To walk", "example": "Ich gehe gern spazieren."}], "grammar": ["Trennbare Verben: einladen, ausgehen, fernsehen, aufstehen", "Perfekt: Ich habe gelesen, Ich bin gegangen", "Modalverben im Kontext: Wollen wir...?, Können wir...?"]},
        5: {"vocab": [{"word": "Schmerzen", "translation": "Pain", "example": "Ich habe Kopfschmerzen."}, {"word": "Fieber", "translation": "Fever", "example": "Ich habe Fieber."}, {"word": "Medikament", "translation": "Medicine", "example": "Nehmen Sie dieses Medikament."}, {"word": "Termin", "translation": "Appointment", "example": "Ich habe einen Arzttermin."}, {"word": "Krank", "translation": "Sick", "example": "Ich bin krank."}, {"word": "Rezept", "translation": "Prescription", "example": "Der Arzt hat mir ein Rezept gegeben."}], "grammar": ["Körperteile mit Artikel: der Kopf, der Bauch, die Hand", "MÜSSEN für Pflicht: Sie müssen mehr trinken", "SOLLEN für Ratschläge: Sie sollen sich ausruhen"]}
    },
    "B1": {
        0: {"vocab": [{"word": "Erfahrung", "translation": "Experience", "example": "Das war eine tolle Erfahrung."}, {"word": "Jemals", "translation": "Ever", "example": "Waren Sie jemals in Berlin?"}, {"word": "Noch nicht", "translation": "Not yet", "example": "Ich habe das noch nicht gemacht."}, {"word": "Kürzlich", "translation": "Recently", "example": "Kürzlich habe ich viel gearbeitet."}, {"word": "Entdecken", "translation": "To discover", "example": "Ich habe ein neues Restaurant entdeckt."}, {"word": "Erreichen", "translation": "To achieve", "example": "Ich habe mein Ziel erreicht."}], "grammar": ["Perfekt mit HABEN und SEIN", "Partizip II: regelmäßig (-t) und unregelmäßig (-en)", "Zeitadverbien: schon, noch nicht, gerade, kürzlich"]},
        1: {"vocab": [{"word": "Rat", "translation": "Advice", "example": "Ich brauche deinen Rat."}, {"word": "Empfehlen", "translation": "To recommend", "example": "Ich empfehle dieses Buch."}, {"word": "Sollte", "translation": "Should", "example": "Du solltest mehr schlafen."}, {"word": "Vorschlagen", "translation": "To suggest", "example": "Ich schlage vor, morgen zu gehen."}, {"word": "Meiner Meinung nach", "translation": "In my opinion", "example": "Meiner Meinung nach ist das richtig."}, {"word": "Lösung", "translation": "Solution", "example": "Es gibt immer eine Lösung."}], "grammar": ["Konjunktiv II: würde + Infinitiv, hätte, wäre", "Konditionalsätze: Wenn ich du wäre, würde ich...", "Indirekte Rede: Er sagt, dass..."]},
        2: {"vocab": [{"word": "Plötzlich", "translation": "Suddenly", "example": "Plötzlich begann es zu regnen."}, {"word": "Während", "translation": "While/During", "example": "Während ich kochte, klingelte das Telefon."}, {"word": "Damals", "translation": "Back then", "example": "Damals war alles anders."}, {"word": "Erinnerung", "translation": "Memory", "example": "Ich habe schöne Erinnerungen."}, {"word": "Geschehen", "translation": "To happen", "example": "Was ist geschehen?"}, {"word": "Schließlich", "translation": "Finally", "example": "Schließlich kam er nach Hause."}], "grammar": ["Präteritum der Modalverben: konnte, musste, wollte", "Nebensätze mit ALS und WENN", "Plusquamperfekt: hatte gemacht, war gegangen"]},
        3: {"vocab": [{"word": "Meinung", "translation": "Opinion", "example": "Was ist Ihre Meinung dazu?"}, {"word": "Zustimmen", "translation": "To agree", "example": "Ich stimme Ihnen zu."}, {"word": "Jedoch", "translation": "However", "example": "Es ist gut, jedoch teuer."}, {"word": "Außerdem", "translation": "Furthermore", "example": "Außerdem ist es gesund."}, {"word": "Deshalb", "translation": "Therefore", "example": "Es regnete, deshalb blieben wir."}, {"word": "Standpunkt", "translation": "Point of view", "example": "Von meinem Standpunkt aus..."}], "grammar": ["Konnektoren: deshalb, trotzdem, außerdem, jedoch", "Nebensätze mit DASS und OB", "Passiv: Es wird gemacht, Es wurde gebaut"]},
        4: {"vocab": [{"word": "Reise", "translation": "Trip", "example": "Die Reise war wunderbar."}, {"word": "Gepäck", "translation": "Luggage", "example": "Mein Gepäck ist nicht angekommen."}, {"word": "Reservierung", "translation": "Reservation", "example": "Ich habe eine Reservierung."}, {"word": "Reisepass", "translation": "Passport", "example": "Vergessen Sie Ihren Reisepass nicht."}, {"word": "Sehenswürdigkeit", "translation": "Sight/Attraction", "example": "Berlin hat viele Sehenswürdigkeiten."}, {"word": "Reiseführer", "translation": "Tour guide", "example": "Der Reiseführer war sehr informativ."}], "grammar": ["Relativsätze: Der Mann, der dort steht...", "Genitiv: des Mannes, der Frau, des Kindes", "Futur I: Ich werde reisen"]},
        5: {"vocab": [{"word": "Kultur", "translation": "Culture", "example": "Die deutsche Kultur ist vielfältig."}, {"word": "Tradition", "translation": "Tradition", "example": "Oktoberfest ist eine deutsche Tradition."}, {"word": "Gemälde", "translation": "Painting", "example": "Das Gemälde ist wunderschön."}, {"word": "Dichter", "translation": "Poet", "example": "Goethe war ein berühmter Dichter."}, {"word": "Einfluss", "translation": "Influence", "example": "Bach hatte großen Einfluss."}, {"word": "Erbe", "translation": "Heritage", "example": "Das kulturelle Erbe Deutschlands."}], "grammar": ["Relativpronomen: der, die, das, dem, den", "Adjektivdeklination nach Artikeln", "Passiv Präteritum: wurde gebaut, wurde geschrieben"]}
    },
    "B2": {
        0: {"vocab": [{"word": "Konjunktiv", "translation": "Subjunctive", "example": "Der Konjunktiv drückt Wünsche aus."}, {"word": "Obwohl", "translation": "Although", "example": "Obwohl es regnete, ging ich spazieren."}, {"word": "Falls", "translation": "In case", "example": "Falls du kommst, ruf mich an."}, {"word": "Sofern", "translation": "Provided that", "example": "Sofern alles klappt, fahren wir."}, {"word": "Angenommen", "translation": "Assuming", "example": "Angenommen, du hättest Geld..."}, {"word": "Andernfalls", "translation": "Otherwise", "example": "Lerne fleißig, andernfalls bestehst du nicht."}], "grammar": ["Konjunktiv II Vergangenheit: hätte gemacht, wäre gegangen", "Irreale Bedingungssätze: Wenn ich gewusst hätte...", "Konzessivsätze: obwohl, trotzdem, dennoch"]},
        1: {"vocab": [{"word": "Vorstellungsgespräch", "translation": "Job interview", "example": "Ich habe morgen ein Vorstellungsgespräch."}, {"word": "Berufserfahrung", "translation": "Work experience", "example": "Ich habe fünf Jahre Berufserfahrung."}, {"word": "Beförderung", "translation": "Promotion", "example": "Sie bekam eine Beförderung."}, {"word": "Frist", "translation": "Deadline", "example": "Die Frist ist am Freitag."}, {"word": "Fähigkeiten", "translation": "Skills", "example": "Zu meinen Fähigkeiten gehören..."}, {"word": "Unternehmen", "translation": "Company", "example": "Das Unternehmen wächst schnell."}], "grammar": ["Nominalstil: die Durchführung, die Bearbeitung", "Konjunktiv I in der indirekten Rede", "Passiv mit Modalverben: Es muss gemacht werden"]},
        2: {"vocab": [{"word": "Klimawandel", "translation": "Climate change", "example": "Der Klimawandel betrifft alle."}, {"word": "Erneuerbare Energie", "translation": "Renewable energy", "example": "Deutschland nutzt viel erneuerbare Energie."}, {"word": "Umweltschutz", "translation": "Environmental protection", "example": "Umweltschutz ist wichtig."}, {"word": "Verschmutzung", "translation": "Pollution", "example": "Die Luftverschmutzung ist ein Problem."}, {"word": "Nachhaltigkeit", "translation": "Sustainability", "example": "Nachhaltigkeit sollte Priorität sein."}, {"word": "CO2-Fußabdruck", "translation": "Carbon footprint", "example": "Wir müssen den CO2-Fußabdruck reduzieren."}], "grammar": ["Finalsätze: damit, um...zu", "Partizipialattribute: die vom Staat geförderte Energie", "Zustandspassiv: Die Tür ist geöffnet"]},
        3: {"vocab": [{"word": "Meisterwerk", "translation": "Masterpiece", "example": "Das ist ein Meisterwerk der Musik."}, {"word": "Ausstellung", "translation": "Exhibition", "example": "Wir besuchten eine Kunstausstellung."}, {"word": "Zeitgenössisch", "translation": "Contemporary", "example": "Zeitgenössische Kunst ist interessant."}, {"word": "Kulturerbe", "translation": "Cultural heritage", "example": "Das Kulturerbe muss bewahrt werden."}, {"word": "Einflussreich", "translation": "Influential", "example": "Beethoven war sehr einflussreich."}, {"word": "Kreativität", "translation": "Creativity", "example": "Kreativität ist in der Kunst wichtig."}], "grammar": ["Relativsätze mit Präpositionen: der Mann, mit dem ich sprach", "Partizip I als Adjektiv: der singende Vogel", "Konjunktiv II der Vergangenheit für Wünsche"]},
        4: {"vocab": [{"word": "Künstliche Intelligenz", "translation": "Artificial intelligence", "example": "KI verändert die Medizin."}, {"word": "Innovation", "translation": "Innovation", "example": "Innovation treibt das Wachstum an."}, {"word": "Datenschutz", "translation": "Data privacy", "example": "Datenschutz ist in Deutschland wichtig."}, {"word": "Automatisierung", "translation": "Automation", "example": "Automatisierung verändert die Industrie."}, {"word": "Digitale Kluft", "translation": "Digital divide", "example": "Die digitale Kluft betrifft ländliche Gebiete."}, {"word": "Cybersicherheit", "translation": "Cybersecurity", "example": "Cybersicherheit ist eine Priorität."}], "grammar": ["Futur II: wird gemacht haben", "Vermutungen mit DÜRFTE: Das dürfte stimmen", "Erweiterte Partizipialattribute"]},
        5: {"vocab": [{"word": "Gesellschaft", "translation": "Society", "example": "Die Gesellschaft verändert sich."}, {"word": "Gleichberechtigung", "translation": "Equal rights", "example": "Gleichberechtigung ist ein Grundrecht."}, {"word": "Integration", "translation": "Integration", "example": "Integration erfordert gegenseitigen Respekt."}, {"word": "Demokratie", "translation": "Democracy", "example": "Demokratie braucht aktive Bürger."}, {"word": "Vielfalt", "translation": "Diversity", "example": "Vielfalt bereichert die Gesellschaft."}, {"word": "Solidarität", "translation": "Solidarity", "example": "Solidarität ist in Krisenzeiten wichtig."}], "grammar": ["Doppelkonjunktionen: sowohl...als auch, weder...noch", "Konsekutivsätze: so...dass, sodass", "Modalpartikeln: doch, ja, mal, eben, halt"]}
    },
    "C1": {
        0: {"vocab": [{"word": "These", "translation": "Thesis", "example": "Die zentrale These des Artikels..."}, {"word": "Vorurteil", "translation": "Bias/Prejudice", "example": "Vorurteile erkennen ist wichtig."}, {"word": "Behauptung", "translation": "Claim/Assertion", "example": "Diese Behauptung ist fragwürdig."}, {"word": "Gegenargument", "translation": "Counterargument", "example": "Es gibt starke Gegenargumente."}, {"word": "Beleg", "translation": "Evidence", "example": "Die Belege stützen die These."}, {"word": "Nuance", "translation": "Nuance", "example": "Die Frage hat viele Nuancen."}], "grammar": ["Partizipialkonstruktionen als Satzverkürzer", "Nominalstil im akademischen Deutsch", "Konnektoren höherer Ebene: nichtsdestotrotz, infolgedessen"]},
        1: {"vocab": [{"word": "Abhandlung", "translation": "Treatise/Paper", "example": "Die Abhandlung behandelt Sprachpolitik."}, {"word": "Verfassen", "translation": "To compose/write", "example": "Er verfasste einen Aufsatz."}, {"word": "Absatz", "translation": "Paragraph", "example": "Jeder Absatz braucht eine Kernaussage."}, {"word": "Kohärenz", "translation": "Coherence", "example": "Der Text hat gute Kohärenz."}, {"word": "Zusammenfassung", "translation": "Summary", "example": "Die Zusammenfassung fasst alles zusammen."}, {"word": "Überleitung", "translation": "Transition", "example": "Gute Überleitungen verbessern den Text."}], "grammar": ["Wissenschaftlicher Stil: Passiv, Nominalstil, Hedging", "Zitierweisen: laut, zufolge, gemäß + Dativ", "Komplexe Satzgefüge mit mehreren Nebensätzen"]},
        2: {"vocab": [{"word": "Dialekt", "translation": "Dialect", "example": "Bayerisch ist ein bekannter Dialekt."}, {"word": "Hochdeutsch", "translation": "Standard German", "example": "Hochdeutsch wird überall verstanden."}, {"word": "Mundart", "translation": "Regional speech", "example": "Jede Region hat ihre Mundart."}, {"word": "Umgangssprache", "translation": "Colloquial language", "example": "In der Umgangssprache sagt man..."}, {"word": "Aussprache", "translation": "Pronunciation", "example": "Die Aussprache variiert regional."}, {"word": "Sprachvarietät", "translation": "Language variety", "example": "Es gibt viele Sprachvarietäten."}], "grammar": ["Regionale Unterschiede: Perfekt vs. Präteritum", "Dialektale Grammatik: bayerisch, schwäbisch, sächsisch", "Stilebenen: formell, informell, umgangssprachlich"]},
        3: {"vocab": [{"word": "Geschäftspartner", "translation": "Business partner", "example": "Unsere Geschäftspartner sind zufrieden."}, {"word": "Verhandlung", "translation": "Negotiation", "example": "Die Verhandlung war erfolgreich."}, {"word": "Angebot", "translation": "Offer/Proposal", "example": "Wir unterbreiten Ihnen ein Angebot."}, {"word": "Bedingungen", "translation": "Terms/Conditions", "example": "Die Bedingungen sind akzeptabel."}, {"word": "Vereinbarung", "translation": "Agreement", "example": "Wir trafen eine Vereinbarung."}, {"word": "Zusammenarbeit", "translation": "Cooperation", "example": "Die Zusammenarbeit war fruchtbar."}], "grammar": ["Höflichkeitsformen: Konjunktiv II, würde-Form", "Geschäftsbriefe: Sehr geehrte Damen und Herren", "Indirekte Rede im Geschäftsdeutsch"]},
        4: {"vocab": [{"word": "Kompromiss", "translation": "Compromise", "example": "Wir fanden einen Kompromiss."}, {"word": "Vorschlag", "translation": "Proposal", "example": "Ich mache einen Vorschlag."}, {"word": "Zugeständnis", "translation": "Concession", "example": "Beide Seiten machten Zugeständnisse."}, {"word": "Strategie", "translation": "Strategy", "example": "Die Verhandlungsstrategie war klug."}, {"word": "Diplomatie", "translation": "Diplomacy", "example": "Diplomatie erfordert Geduld."}, {"word": "Lösung", "translation": "Solution", "example": "Wir suchen eine gemeinsame Lösung."}], "grammar": ["Konsekutiv- und Finalsätze in Verhandlungen", "Diplomatische Sprache: Abschwächungen und Höflichkeit", "Präsentationstechniken: Redemittel und Struktur"]},
        5: {"vocab": [{"word": "Erzählung", "translation": "Narrative", "example": "Die Erzählung ist fesselnd."}, {"word": "Symbolik", "translation": "Symbolism", "example": "Die Symbolik ist tiefgründig."}, {"word": "Metapher", "translation": "Metaphor", "example": "Der Autor verwendet starke Metaphern."}, {"word": "Perspektive", "translation": "Perspective", "example": "Die Erzählperspektive wechselt."}, {"word": "Rezension", "translation": "Review", "example": "Ich schrieb eine Rezension."}, {"word": "Strömung", "translation": "Movement/Current", "example": "Der Expressionismus war eine Strömung."}], "grammar": ["Literarisches Präsens vs. Erzählpräteritum", "Stilmittel: Metapher, Allegorie, Ironie", "Textanalyse: Argumentationsstruktur erkennen"]}
    },
    "C2": {
        0: {"vocab": [{"word": "Paradigma", "translation": "Paradigm", "example": "Ein Paradigmenwechsel in der Forschung."}, {"word": "Empirie", "translation": "Empiricism", "example": "Die empirische Forschung bestätigt dies."}, {"word": "Diskurs", "translation": "Discourse", "example": "Der akademische Diskurs ist komplex."}, {"word": "Korrelation", "translation": "Correlation", "example": "Es gibt eine Korrelation zwischen..."}, {"word": "Hypothese", "translation": "Hypothesis", "example": "Die Hypothese wurde bestätigt."}, {"word": "Methodik", "translation": "Methodology", "example": "Die Methodik ist solide."}], "grammar": ["Wissenschaftliche Passivkonstruktionen", "Konjunktiv I in der indirekten Rede (akademisch)", "Nominalisierungen für formellen Stil"]},
        1: {"vocab": [{"word": "Sprechakt", "translation": "Speech act", "example": "Bitten ist ein indirekter Sprechakt."}, {"word": "Höflichkeit", "translation": "Politeness", "example": "Höflichkeit variiert zwischen Kulturen."}, {"word": "Implikatur", "translation": "Implicature", "example": "Die Implikatur hängt vom Kontext ab."}, {"word": "Abschwächung", "translation": "Mitigation", "example": "Abschwächungen sind im Deutschen üblich."}, {"word": "Mehrdeutigkeit", "translation": "Ambiguity", "example": "Sprachliche Mehrdeutigkeit kann Missverständnisse verursachen."}, {"word": "Kontext", "translation": "Context", "example": "Der Kontext bestimmt die Bedeutung."}], "grammar": ["Indirekte Sprechakte im Deutschen", "Modalpartikeln als pragmatische Mittel", "Stilistische Variation in verschiedenen Registern"]},
        2: {"vocab": [{"word": "Falsche Freunde", "translation": "False friends", "example": "'Bekommen' heißt 'to get', nicht 'to become'."}, {"word": "Lokalisierung", "translation": "Localization", "example": "Lokalisierung passt Inhalte an."}, {"word": "Ausgangssprache", "translation": "Source language", "example": "Die Ausgangssprache ist Deutsch."}, {"word": "Zielsprache", "translation": "Target language", "example": "Englisch ist die Zielsprache."}, {"word": "Äquivalenz", "translation": "Equivalence", "example": "Exakte Äquivalenz ist selten möglich."}, {"word": "Treue", "translation": "Faithfulness", "example": "Treue zum Original ist wichtig."}], "grammar": ["Syntaktische Unterschiede Deutsch-Englisch", "Lehnwörter und Fremdwörter im Deutschen", "Register und Stil in der Übersetzung beibehalten"]},
        3: {"vocab": [{"word": "Rhetorik", "translation": "Rhetoric", "example": "Rhetorik ist die Kunst der Überzeugung."}, {"word": "Redekunst", "translation": "Oratory", "example": "Die Redekunst erfordert Übung."}, {"word": "Überzeugung", "translation": "Persuasion", "example": "Effektive Überzeugung kombiniert Logik und Emotion."}, {"word": "Anapher", "translation": "Anaphora", "example": "Die Anapher verstärkt die Botschaft."}, {"word": "Antithese", "translation": "Antithesis", "example": "Die Antithese schafft dramatischen Kontrast."}, {"word": "Beredsamkeit", "translation": "Eloquence", "example": "Seine Beredsamkeit beeindruckte alle."}], "grammar": ["Invertierter Satzbau für rhetorische Wirkung", "Parallelismus in der Rede", "Konjunktiv für rhetorische Fragen"]},
        4: {"vocab": [{"word": "Soziolekt", "translation": "Sociolect", "example": "Jede Gruppe hat ihren Soziolekt."}, {"word": "Neologismus", "translation": "Neologism", "example": "'Googeln' ist ein Neologismus."}, {"word": "Sprachpolitik", "translation": "Language policy", "example": "Sprachpolitik beeinflusst die Bildung."}, {"word": "Zweisprachigkeit", "translation": "Bilingualism", "example": "Zweisprachigkeit ist ein Vorteil."}, {"word": "Sprachwandel", "translation": "Language change", "example": "Sprachwandel ist natürlich."}, {"word": "Standardisierung", "translation": "Standardization", "example": "Die Standardisierung hat politische Folgen."}], "grammar": ["Deskriptive vs. präskriptive Grammatik", "Grammatikalisierung: Bedeutungswandel über Zeit", "Aktuelle Sprachentwicklungen: gendern, Anglizismen"]},
        5: {"vocab": [{"word": "Prosa", "translation": "Prose", "example": "Seine Prosa ist elegant."}, {"word": "Erzählstimme", "translation": "Narrative voice", "example": "Die Erzählstimme ist intim."}, {"word": "Bildsprache", "translation": "Imagery", "example": "Die Bildsprache ist eindrucksvoll."}, {"word": "Prägnanz", "translation": "Conciseness", "example": "Gutes Schreiben erfordert Prägnanz."}, {"word": "Glaubwürdigkeit", "translation": "Credibility", "example": "Fiktion braucht Glaubwürdigkeit."}, {"word": "Überarbeitung", "translation": "Revision", "example": "Gutes Schreiben ist Überarbeitung."}], "grammar": ["Stilvariation: einfache und komplexe Satzstrukturen", "Literarische Stilmittel: Metapher, Personifikation", "Erzähltempus: Präsens für Unmittelbarkeit, Präteritum für Reflexion"]}
    }
}

# French vocabulary fix - similar structure
FRENCH_VOCAB = {
    "A2": {
        0: {"vocab": [{"word": "Grand/Petit", "translation": "Big/Small", "example": "La maison est très grande."}, {"word": "Sympathique", "translation": "Friendly/Nice", "example": "Les Français sont sympathiques."}, {"word": "Beau/Belle", "translation": "Beautiful", "example": "Paris est une belle ville."}, {"word": "Calme", "translation": "Quiet/Calm", "example": "Le village est très calme."}, {"word": "Cheveux", "translation": "Hair", "example": "Elle a les cheveux longs."}, {"word": "Yeux", "translation": "Eyes", "example": "Il a les yeux bleus."}], "grammar": ["Accord des adjectifs: grand/grande, beau/belle", "Être pour les descriptions permanentes", "Avoir pour décrire: Il a les yeux bleus"]},
        1: {"vocab": [{"word": "Combien ça coûte?", "translation": "How much?", "example": "Combien coûte cette robe?"}, {"word": "Bon marché/Cher", "translation": "Cheap/Expensive", "example": "Ce sac est trop cher."}, {"word": "Taille", "translation": "Size", "example": "Vous avez en taille M?"}, {"word": "Essayer", "translation": "To try on", "example": "Je peux essayer cette robe?"}, {"word": "Espèces", "translation": "Cash", "example": "Je peux payer en espèces?"}, {"word": "Soldes", "translation": "Sales/Discount", "example": "Les soldes commencent demain."}], "grammar": ["Comparatif: plus/moins + adjectif + que", "Démonstratifs: ce, cette, ces, celui-ci", "Pronoms COD: le, la, les"]},
        2: {"vocab": [{"word": "Il fait chaud", "translation": "It's hot", "example": "En été il fait très chaud."}, {"word": "Pluie", "translation": "Rain", "example": "Il y a beaucoup de pluie."}, {"word": "Nuageux", "translation": "Cloudy", "example": "Aujourd'hui il fait nuageux."}, {"word": "Printemps", "translation": "Spring", "example": "Au printemps les fleurs sont belles."}, {"word": "Parapluie", "translation": "Umbrella", "example": "Prends ton parapluie."}, {"word": "Degrés", "translation": "Degrees", "example": "Il fait 30 degrés."}], "grammar": ["FAIRE pour la météo: il fait chaud, il fait froid", "Le futur proche: Il va pleuvoir demain", "Le présent continu: Il est en train de pleuvoir"]},
        3: {"vocab": [{"word": "Droite/Gauche", "translation": "Right/Left", "example": "Tournez à droite."}, {"word": "Près/Loin", "translation": "Near/Far", "example": "L'hôtel est près du centre."}, {"word": "Coin", "translation": "Corner", "example": "La pharmacie est au coin."}, {"word": "Arrêt", "translation": "Stop", "example": "L'arrêt de bus est ici."}, {"word": "Rue", "translation": "Street", "example": "J'habite rue Victor Hugo."}, {"word": "Traverser", "translation": "To cross", "example": "Traversez la rue et tournez à gauche."}], "grammar": ["Impératif: allez, tournez, prenez", "Prépositions de lieu: à côté de, en face de, entre", "Le verbe ALLER: je vais, tu vas, il va"]},
        4: {"vocab": [{"word": "Temps libre", "translation": "Free time", "example": "Pendant mon temps libre, je lis."}, {"word": "Week-end", "translation": "Weekend", "example": "Ce week-end je vais à la plage."}, {"word": "Film", "translation": "Movie", "example": "On va voir un film ce soir."}, {"word": "Amusant", "translation": "Fun", "example": "La fête était très amusante."}, {"word": "Inviter", "translation": "To invite", "example": "Je t'invite à dîner vendredi."}, {"word": "Se promener", "translation": "To walk", "example": "J'aime me promener dans le parc."}], "grammar": ["ALLER + infinitif pour le futur proche", "POUVOIR: je peux, tu peux, il peut", "VOULOIR + infinitif: Tu veux aller au cinéma?"]},
        5: {"vocab": [{"word": "Douleur", "translation": "Pain", "example": "J'ai mal à la tête."}, {"word": "Fièvre", "translation": "Fever", "example": "J'ai de la fièvre."}, {"word": "Médicament", "translation": "Medicine", "example": "Prenez ce médicament."}, {"word": "Rendez-vous", "translation": "Appointment", "example": "J'ai un rendez-vous médical."}, {"word": "Malade", "translation": "Sick", "example": "Je suis malade."}, {"word": "Ordonnance", "translation": "Prescription", "example": "Le médecin m'a donné une ordonnance."}], "grammar": ["AVOIR MAL À: J'ai mal à la tête, au ventre", "DEVOIR + infinitif: Vous devez vous reposer", "IL FAUT + infinitif: Il faut boire beaucoup"]}
    },
    "B1": {
        0: {"vocab": [{"word": "Expérience", "translation": "Experience", "example": "C'était une expérience incroyable."}, {"word": "Jamais", "translation": "Ever/Never", "example": "Avez-vous jamais visité Paris?"}, {"word": "Pas encore", "translation": "Not yet", "example": "Je n'ai pas encore fini."}, {"word": "Récemment", "translation": "Recently", "example": "Récemment, j'ai beaucoup travaillé."}, {"word": "Découvrir", "translation": "To discover", "example": "J'ai découvert un nouveau restaurant."}, {"word": "Réussir", "translation": "To succeed", "example": "J'ai réussi mon examen."}], "grammar": ["Passé composé avec AVOIR et ÊTRE", "Participes passés irréguliers: fait, dit, écrit, vu", "Marqueurs temporels: déjà, pas encore, jamais"]},
        1: {"vocab": [{"word": "Conseil", "translation": "Advice", "example": "J'ai besoin de tes conseils."}, {"word": "Recommander", "translation": "To recommend", "example": "Je recommande ce livre."}, {"word": "Devrait", "translation": "Should", "example": "Tu devrais te reposer."}, {"word": "Suggérer", "translation": "To suggest", "example": "Je suggère qu'on parte tôt."}, {"word": "À mon avis", "translation": "In my opinion", "example": "À mon avis, c'est une bonne idée."}, {"word": "Solution", "translation": "Solution", "example": "Il y a toujours une solution."}], "grammar": ["Conditionnel présent: je parlerais, je mangerais", "SI + imparfait + conditionnel: Si j'étais toi, je...", "Subjonctif avec verbes de suggestion: Je suggère que tu viennes"]},
        2: {"vocab": [{"word": "Soudain", "translation": "Suddenly", "example": "Soudain, il a commencé à pleuvoir."}, {"word": "Pendant que", "translation": "While", "example": "Pendant que je cuisinais, le téléphone a sonné."}, {"word": "À l'époque", "translation": "At that time", "example": "À l'époque, tout était différent."}, {"word": "Souvenir", "translation": "Memory", "example": "J'ai de beaux souvenirs."}, {"word": "Se passer", "translation": "To happen", "example": "Que s'est-il passé?"}, {"word": "Finalement", "translation": "Finally", "example": "Finalement, il est rentré."}], "grammar": ["Passé composé vs imparfait: action vs description", "Plus-que-parfait: avait fait, était allé", "Connecteurs narratifs: d'abord, ensuite, enfin"]},
        3: {"vocab": [{"word": "Opinion", "translation": "Opinion", "example": "Quelle est votre opinion?"}, {"word": "Être d'accord", "translation": "To agree", "example": "Je suis d'accord avec toi."}, {"word": "Cependant", "translation": "However", "example": "C'est bon, cependant c'est cher."}, {"word": "De plus", "translation": "Furthermore", "example": "De plus, c'est bon pour la santé."}, {"word": "Par conséquent", "translation": "Therefore", "example": "Il pleuvait, par conséquent nous sommes restés."}, {"word": "Point de vue", "translation": "Point of view", "example": "De mon point de vue..."}], "grammar": ["Connecteurs logiques: cependant, néanmoins, de plus", "Subjonctif après expressions d'opinion négative", "Discours rapporté: Il a dit que..."]},
        4: {"vocab": [{"word": "Voyage", "translation": "Trip", "example": "Le voyage était merveilleux."}, {"word": "Bagages", "translation": "Luggage", "example": "Mes bagages ne sont pas arrivés."}, {"word": "Réservation", "translation": "Reservation", "example": "J'ai une réservation."}, {"word": "Passeport", "translation": "Passport", "example": "N'oubliez pas votre passeport."}, {"word": "Curiosité", "translation": "Sight/Attraction", "example": "Paris a beaucoup de curiosités."}, {"word": "Guide", "translation": "Tour guide", "example": "Le guide était très intéressant."}], "grammar": ["Pronoms relatifs: qui, que, dont, où", "Le gérondif: en voyageant, en mangeant", "Y et EN: J'y vais, J'en viens"]},
        5: {"vocab": [{"word": "Culture", "translation": "Culture", "example": "La culture française est riche."}, {"word": "Gastronomie", "translation": "Gastronomy", "example": "La gastronomie française est célèbre."}, {"word": "Patrimoine", "translation": "Heritage", "example": "Le patrimoine culturel français."}, {"word": "Cinéma", "translation": "Cinema", "example": "Le cinéma français est reconnu."}, {"word": "Influence", "translation": "Influence", "example": "La France a eu une grande influence."}, {"word": "Tradition", "translation": "Tradition", "example": "Les traditions sont importantes."}], "grammar": ["Pronoms démonstratifs: celui, celle, ceux, celles", "Mise en relief: C'est...qui, C'est...que", "Voix passive: a été construit, a été écrit"]}
    },
    "B2": {
        0: {"vocab": [{"word": "Subjonctif", "translation": "Subjunctive", "example": "Il faut que tu viennes."}, {"word": "Bien que", "translation": "Although", "example": "Bien qu'il pleuve, je sors."}, {"word": "À moins que", "translation": "Unless", "example": "J'irai à moins qu'il pleuve."}, {"word": "Pour que", "translation": "So that", "example": "Je t'explique pour que tu comprennes."}, {"word": "Avant que", "translation": "Before", "example": "Avant que tu partes, ferme la fenêtre."}, {"word": "Jusqu'à ce que", "translation": "Until", "example": "J'attendrai jusqu'à ce que tu viennes."}], "grammar": ["Subjonctif présent: formation et usage", "Indicatif vs subjonctif: certitude vs doute", "Conjonctions + subjonctif: bien que, pour que, avant que"]},
        1: {"vocab": [{"word": "Entretien", "translation": "Interview", "example": "J'ai un entretien d'embauche."}, {"word": "Expérience professionnelle", "translation": "Work experience", "example": "J'ai cinq ans d'expérience."}, {"word": "Promotion", "translation": "Promotion", "example": "Elle a eu une promotion."}, {"word": "Délai", "translation": "Deadline", "example": "Le délai est vendredi."}, {"word": "Compétences", "translation": "Skills", "example": "Mes compétences incluent..."}, {"word": "Entreprise", "translation": "Company", "example": "L'entreprise se développe."}], "grammar": ["Nominalisation: analyser → l'analyse", "Conditionnel passé: j'aurais fait, je serais allé", "Discours rapporté au passé"]},
        2: {"vocab": [{"word": "Changement climatique", "translation": "Climate change", "example": "Le changement climatique nous concerne tous."}, {"word": "Énergie renouvelable", "translation": "Renewable energy", "example": "La France investit dans les énergies renouvelables."}, {"word": "Développement durable", "translation": "Sustainable development", "example": "Le développement durable est essentiel."}, {"word": "Pollution", "translation": "Pollution", "example": "La pollution de l'air est grave."}, {"word": "Empreinte carbone", "translation": "Carbon footprint", "example": "Réduisons notre empreinte carbone."}, {"word": "Recyclage", "translation": "Recycling", "example": "Le recyclage est important."}], "grammar": ["Subjonctif avec expressions d'urgence", "Conditionnel 3: Si + plus-que-parfait + conditionnel passé", "Voix passive pour les processus: est fabriqué, a été construit"]},
        3: {"vocab": [{"word": "Chef-d'oeuvre", "translation": "Masterpiece", "example": "La Joconde est un chef-d'oeuvre."}, {"word": "Exposition", "translation": "Exhibition", "example": "Nous avons visité une exposition."}, {"word": "Contemporain", "translation": "Contemporary", "example": "L'art contemporain est intéressant."}, {"word": "Patrimoine", "translation": "Heritage", "example": "Le patrimoine doit être préservé."}, {"word": "Influence", "translation": "Influence", "example": "L'impressionnisme a eu une grande influence."}, {"word": "Créativité", "translation": "Creativity", "example": "La créativité est essentielle."}], "grammar": ["Pronoms relatifs composés: lequel, auquel, duquel", "Participe présent et gérondif", "Phrase emphatique: Ce qui me plaît, c'est..."]},
        4: {"vocab": [{"word": "Intelligence artificielle", "translation": "AI", "example": "L'IA transforme la médecine."}, {"word": "Innovation", "translation": "Innovation", "example": "L'innovation technologique progresse."}, {"word": "Vie privée", "translation": "Privacy", "example": "La vie privée en ligne est importante."}, {"word": "Automatisation", "translation": "Automation", "example": "L'automatisation a changé l'industrie."}, {"word": "Fracture numérique", "translation": "Digital divide", "example": "La fracture numérique persiste."}, {"word": "Cybersécurité", "translation": "Cybersecurity", "example": "La cybersécurité est une priorité."}], "grammar": ["Futur antérieur: aura transformé, sera devenu", "Expressions de probabilité: il est probable que + subjonctif", "Phrases clivées: C'est la technologie qui..."]},
        5: {"vocab": [{"word": "Société", "translation": "Society", "example": "La société évolue rapidement."}, {"word": "Égalité", "translation": "Equality", "example": "L'égalité est un droit fondamental."}, {"word": "Intégration", "translation": "Integration", "example": "L'intégration demande du respect mutuel."}, {"word": "Démocratie", "translation": "Democracy", "example": "La démocratie a besoin de citoyens actifs."}, {"word": "Diversité", "translation": "Diversity", "example": "La diversité enrichit la société."}, {"word": "Solidarité", "translation": "Solidarity", "example": "La solidarité est importante en crise."}], "grammar": ["Doubles conjonctions: non seulement...mais aussi", "Consécutives: si...que, tellement...que", "Registre soutenu vs courant"]}
    },
    "C1": {i: {"vocab": [{"word": w, "translation": t, "example": e} for w,t,e in vlist], "grammar": glist} for i, (vlist, glist) in enumerate([
        ([("Thèse", "Thesis", "La thèse centrale de l'article..."), ("Préjugé", "Bias", "Reconnaître les préjugés."), ("Affirmation", "Claim", "Cette affirmation est discutable."), ("Contre-argument", "Counterargument", "Il y a des contre-arguments."), ("Preuve", "Evidence", "Les preuves soutiennent la thèse."), ("Nuance", "Nuance", "La question a beaucoup de nuances.")], ["Connecteurs de reformulation: c'est-à-dire, en d'autres termes", "Propositions concessives: bien que, quoique + subjonctif", "Nominalisation pour le registre académique"]),
        ([("Dissertation", "Essay", "J'ai écrit une dissertation."), ("Rédiger", "To write/draft", "Il a rédigé un rapport."), ("Paragraphe", "Paragraph", "Chaque paragraphe a une idée."), ("Cohésion", "Cohesion", "Le texte a une bonne cohésion."), ("Synthèse", "Synthesis", "La conclusion fait une synthèse."), ("Transition", "Transition", "Les transitions entre paragraphes.")], ["Style impersonnel: on, il est + adjectif + que", "Citations: selon, d'après, conformément à", "Phrases complexes avec subordination multiple"]),
        ([("Dialecte", "Dialect", "Le québécois est un dialecte."), ("Accent", "Accent", "Elle a un fort accent du Midi."), ("Argot", "Slang", "L'argot varie entre générations."), ("Francophonie", "French-speaking world", "La francophonie s'étend sur 5 continents."), ("Prononciation", "Pronunciation", "La prononciation varie beaucoup."), ("Variété", "Variety", "Chaque pays a sa variété.")], ["Différences lexicales: France vs Québec vs Belgique vs Suisse", "Registres: soutenu, courant, familier, argotique", "Néologismes et emprunts dans le français contemporain"]),
        ([("Partenaire commercial", "Business partner", "Nos partenaires sont satisfaits."), ("Négociation", "Negotiation", "La négociation a abouti."), ("Proposition", "Proposal", "Nous vous soumettons une proposition."), ("Conditions", "Terms", "Les conditions sont acceptables."), ("Accord", "Agreement", "Nous avons trouvé un accord."), ("Coopération", "Cooperation", "La coopération a été fructueuse.")], ["Conditionnel de politesse: pourriez-vous, auriez-vous", "Correspondance commerciale: formules de politesse", "Discours rapporté dans les comptes rendus"]),
        ([("Compromis", "Compromise", "Nous avons trouvé un compromis."), ("Concession", "Concession", "Les deux parties ont fait des concessions."), ("Stratégie", "Strategy", "La stratégie de négociation était habile."), ("Diplomatie", "Diplomacy", "La diplomatie exige de la patience."), ("Objectif", "Objective", "L'objectif est clair."), ("Résultat", "Result", "Les résultats sont positifs.")], ["Techniques de persuasion en français", "Langage diplomatique: atténuations", "Structure de la présentation formelle"]),
        ([("Récit", "Narrative", "Le récit est captivant."), ("Symbolisme", "Symbolism", "Le symbolisme est profond."), ("Métaphore", "Metaphor", "L'auteur utilise des métaphores fortes."), ("Courant littéraire", "Literary movement", "Le surréalisme est un courant."), ("Critique", "Review/Criticism", "La critique littéraire est exigeante."), ("Style", "Style", "Son style est unique.")], ["Présent littéraire vs passé simple narratif", "Figures de style: métaphore, métonymie, litote", "Analyse textuelle: structure argumentative"])
    ])},
    "C2": {i: {"vocab": [{"word": w, "translation": t, "example": e} for w,t,e in vlist], "grammar": glist} for i, (vlist, glist) in enumerate([
        ([("Paradigme", "Paradigm", "Un changement de paradigme."), ("Empirique", "Empirical", "La recherche empirique confirme."), ("Discours", "Discourse", "Le discours académique est complexe."), ("Corrélation", "Correlation", "Il y a une corrélation."), ("Hypothèse", "Hypothesis", "L'hypothèse a été confirmée."), ("Méthodologie", "Methodology", "La méthodologie est rigoureuse.")], ["Constructions passives complexes en français académique", "Subjonctif dans le discours académique formel", "Nominalisation pour le registre soutenu"]),
        ([("Acte de parole", "Speech act", "Demander est un acte de parole indirect."), ("Politesse", "Politeness", "La politesse varie entre cultures."), ("Implicature", "Implicature", "L'implicature dépend du contexte."), ("Atténuation", "Mitigation", "Les atténuations adoucissent le message."), ("Ambiguïté", "Ambiguity", "L'ambiguïté pragmatique peut causer des malentendus."), ("Registre", "Register", "Adaptez votre registre.")], ["Actes de parole indirects en français", "Stratégies de politesse positive et négative", "Marqueurs discursifs: bon, ben, enfin, quoi"]),
        ([("Faux amis", "False friends", "'Librairie' signifie bookstore, pas library."), ("Localisation", "Localization", "La localisation adapte le contenu."), ("Langue source", "Source language", "Le français est la langue source."), ("Langue cible", "Target language", "L'anglais est la langue cible."), ("Équivalence", "Equivalence", "L'équivalence exacte est rare."), ("Fidélité", "Faithfulness", "La fidélité au texte original.")], ["Différences syntaxiques français-anglais", "Anglicismes dans le français contemporain", "Maintenir le registre dans la traduction"]),
        ([("Rhétorique", "Rhetoric", "La rhétorique est l'art de persuader."), ("Éloquence", "Eloquence", "Son éloquence a captivé le public."), ("Persuasion", "Persuasion", "La persuasion efficace combine logique et émotion."), ("Anaphore", "Anaphora", "L'anaphore renforce le message."), ("Antithèse", "Antithesis", "L'antithèse crée un contraste dramatique."), ("Art oratoire", "Oratory", "L'art oratoire demande de la pratique.")], ["Inversion pour l'emphase rhétorique", "Parallélisme dans le discours persuasif", "Figures de style pour la prise de parole"]),
        ([("Sociolecte", "Sociolect", "Chaque groupe a son sociolecte."), ("Néologisme", "Neologism", "'Courriel' est un néologisme québécois."), ("Impérialisme linguistique", "Linguistic imperialism", "Le débat sur l'impérialisme linguistique."), ("Normalisation", "Standardization", "La normalisation linguistique est complexe."), ("Alternance codique", "Code-switching", "L'alternance codique est fréquente."), ("Prescriptivisme", "Prescriptivism", "Le prescriptivisme dicte l'usage correct.")], ["Grammaire descriptive vs prescriptive", "Évolution de la langue: nouvelles formes", "Politique linguistique francophone"]),
        ([("Prose", "Prose", "Sa prose est élégante."), ("Voix narrative", "Narrative voice", "La voix narrative est intime."), ("Imagerie", "Imagery", "L'imagerie est riche."), ("Concision", "Conciseness", "La concision est une vertu littéraire."), ("Vraisemblance", "Verisimilitude", "La fiction a besoin de vraisemblance."), ("Révision", "Revision", "Bien écrire, c'est réécrire.")], ["Variation stylistique dans la structure des phrases", "Procédés littéraires: métaphore, allégorie, ironie", "Choix du temps narratif: présent ou passé"])
    ])}
}

# Portuguese A2 content fix
PORT_A2_CONTENT = [
    "Aprenda adjetivos para descrever aparência e personalidade.\n\nAparência com SER: 'É alto/a' (tall), 'É baixo/a' (short), 'É magro/a' (thin). Com TER: 'Tem olhos azuis', 'Tem cabelo longo'.\n\nPersonalidade: simpático/a (nice), inteligente, tímido/a (shy), alegre (cheerful), sério/a (serious).\n\nLugares: grande, pequeno, bonito, tranquilo, moderno, antigo. 'A minha cidade é grande e moderna. Tem muitos parques.'",
    "Vocabulário e expressões para fazer compras em português.\n\nNa loja de roupas: 'Quanto custa?' (How much?), 'Tem em tamanho maior/menor?' (Do you have a bigger/smaller size?), 'Posso experimentar?' (Can I try it on?), 'Vou levar' (I'll take it).\n\nRoupas: camisa (shirt), calça (pants), vestido (dress), sapatos (shoes), saia (skirt), casaco (jacket).\n\nFormas de pagamento: dinheiro (cash), cartão de crédito (credit card). 'Aceitam cartão?' (Do you accept cards?).",
    "Falar sobre o clima e as estações em português.\n\nPerguntar: 'Como está o tempo?' Respostas: 'Está quente/frio/nublado'. 'Está chovendo' (It's raining).\n\nEstações do ano: primavera, verão, outono, inverno. 'No verão faz muito calor no Brasil'.\n\nTemperaturas: 'A temperatura é de 25 graus'. O Brasil usa Celsius.\n\nExpressões: 'Que dia bonito!', 'A previsão diz que vai chover amanhã', 'Preciso de um guarda-chuva'.",
    "Pedir e dar direções em português, vocabulário de transporte.\n\nPedir: 'Onde fica...?' (Where is...?), 'Como chego a...?' (How do I get to...?), 'Está longe/perto?' (Is it far/near?).\n\nDar direções: 'Siga em frente' (Go straight), 'Vire à direita/esquerda' (Turn right/left), 'Fica na esquina' (It's on the corner).\n\nTransporte: ônibus, táxi, metrô, trem, avião, bicicleta. 'Onde fica a parada de ônibus?' (Where is the bus stop?).",
    "Fazer planos e falar de atividades de lazer em português.\n\nLazer: ler (read), assistir TV (watch TV), ouvir música (listen to music), jogar futebol (play soccer), ir ao cinema (go to movies), sair com amigos (go out with friends).\n\nPlanos: 'Vou + infinitivo'. 'Neste fim de semana vou ao cinema'. 'Quer ir jantar?' (Do you want to go to dinner?).\n\nAceitar: 'Sim, claro!', 'Adoraria!'. Recusar: 'Desculpe, não posso', 'Talvez outro dia'.",
    "Vocabulário médico básico em português para consultas e emergências.\n\nNo médico: 'O que você está sentindo?' (What are you feeling?), 'Estou com dor de...' (I have a pain in...), 'Me sinto mal' (I feel sick).\n\nPartes do corpo: cabeça (head), estômago (stomach), costas (back), garganta (throat), braço (arm), perna (leg).\n\nSintomas: febre (fever), tosse (cough), gripe (flu), alergia (allergy), náusea (nausea).\n\nConselho médico: 'Tome este remédio duas vezes ao dia', 'Precisa descansar'."
]


async def main():
    client = AsyncIOMotorClient(MONGO_URL)
    db = client[DB_NAME]
    updated = 0
    
    # Fix German lessons
    for level, lesson_fixes in GERMAN_VOCAB.items():
        course = await db.courses.find_one({"language": "german", "level": level})
        if not course: continue
        lessons = await db.lessons.find({"course_id": str(course["_id"])}).sort("_id", 1).to_list(None)
        for idx, fix in lesson_fixes.items():
            if idx < len(lessons):
                await db.lessons.update_one({"_id": lessons[idx]["_id"]}, {"$set": {"vocabulary": fix["vocab"], "grammar_points": fix["grammar"]}})
                updated += 1
        print(f"Fixed german-{level}: {len(lesson_fixes)} lessons")
    
    # Fix French lessons
    for level, lesson_fixes in FRENCH_VOCAB.items():
        course = await db.courses.find_one({"language": "french", "level": level})
        if not course: continue
        lessons = await db.lessons.find({"course_id": str(course["_id"])}).sort("_id", 1).to_list(None)
        for idx, fix in lesson_fixes.items():
            if idx < len(lessons):
                await db.lessons.update_one({"_id": lessons[idx]["_id"]}, {"$set": {"vocabulary": fix["vocab"], "grammar_points": fix["grammar"]}})
                updated += 1
        print(f"Fixed french-{level}: {len(lesson_fixes)} lessons")
    
    # Fix Portuguese A2 content
    course = await db.courses.find_one({"language": "portuguese", "level": "A2"})
    if course:
        lessons = await db.lessons.find({"course_id": str(course["_id"])}).sort("_id", 1).to_list(None)
        for i, lesson in enumerate(lessons):
            if i < len(PORT_A2_CONTENT):
                await db.lessons.update_one({"_id": lesson["_id"]}, {"$set": {"content": PORT_A2_CONTENT[i]}})
                updated += 1
        print(f"Fixed portuguese-A2: {len(PORT_A2_CONTENT)} lessons content")
    
    print(f"\nTotal updated: {updated}")
    client.close()

if __name__ == "__main__":
    asyncio.run(main())
